// <auto-generated />
namespace HRiVote.DAL.EntityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ColumninCalendar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColumninCalendar));
        
        string IMigrationMetadata.Id
        {
            get { return "201711021316276_Column in Calendar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
